name: moneynest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  tflite_flutter: ^0.11.0
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.1.6
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.3.2
  flutter_gemini: ^3.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.11.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/models/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/MH.png"