// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMA1Ppm4QPSbp6vnl-Q8VeYFzFUvlTjlQ',
    appId: '1:660641645483:web:dbfbc9e69e545de25ec8ee',
    messagingSenderId: '660641645483',
    projectId: 'finance-6f1a1',
    authDomain: 'finance-6f1a1.firebaseapp.com',
    storageBucket: 'finance-6f1a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NIoZojbB9d6PHaYgSZhpotWC2J7C_cU',
    appId: '1:660641645483:android:caa74882b16c390a5ec8ee',
    messagingSenderId: '660641645483',
    projectId: 'finance-6f1a1',
    storageBucket: 'finance-6f1a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx57j5bbm6bobuV-Wz9tO_n5k8_5TriG0',
    appId: '1:660641645483:ios:db8d3b147ac127905ec8ee',
    messagingSenderId: '660641645483',
    projectId: 'finance-6f1a1',
    storageBucket: 'finance-6f1a1.firebasestorage.app',
    iosClientId: '660641645483-076gm7iu4s7og1vbu2pqmeudtoghhgaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.ft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx57j5bbm6bobuV-Wz9tO_n5k8_5TriG0',
    appId: '1:660641645483:ios:db8d3b147ac127905ec8ee',
    messagingSenderId: '660641645483',
    projectId: 'finance-6f1a1',
    storageBucket: 'finance-6f1a1.firebasestorage.app',
    iosClientId: '660641645483-076gm7iu4s7og1vbu2pqmeudtoghhgaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.ft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMA1Ppm4QPSbp6vnl-Q8VeYFzFUvlTjlQ',
    appId: '1:660641645483:web:cc5c6a625cb0b8875ec8ee',
    messagingSenderId: '660641645483',
    projectId: 'finance-6f1a1',
    authDomain: 'finance-6f1a1.firebaseapp.com',
    storageBucket: 'finance-6f1a1.firebasestorage.app',
  );
}
